#+include: ~/org/latex.org

Momentum

Some notes about momentum, and particularly angular momentum.

* Definition

In the broad sense, momentum is /only/ defined as the partial
derivative of the Lagrangian with respect to velocity:

\[ p = \ddd{\LL}{v}(q, v) \]

In fact, only the /kinectic energy/ $T = \half v^T M v$ actually plays
a role in it, where $M(q)$ is the inertia at current
configuration. Thus, the general expression of momentum is:

\[ p = M v \]

Note that $p, v$ and $M$ depend on the choice of
coordinate-frame. There can be a body-fixed, or spatial momentum, or
even using some other coordinate frame. See the notes on [[../math/group/lie-groups.org][Lie groups]]
for more details.

** Rigid Bodies

   In the case of [[./rigid.org][rigid]] bodies, the momentum is usually split between
   linear and angular parts. The /classical/ definition of angular
   momentum about a point $r$ is:

   \[ L(r) = \int_\Omega \rho(x) (x - r) \times v(x) \ \dd x \]

   In body-fixed coordinates, this reads:

   \[ L(r) = \int_\Omega \rho(x) \block{x - R^T (r - c)} \times \block{v + \omega \times x} \dd x\]

   Put roughly, the angular momentum (continuously) aggregates the
   momentum due to each particle in the object, pulled according to
   the rigid-point mapping. More precisely:

   \[ L(r) = \int_\Omega \rho(x) (x - c) \times v(x) \]

   


** Usual angular momentum definition
   


