Special Euclidean Group
 
The Special Euclidean Group, noted $SE(n)$, is the group of affine
maps that preserve the Euclidean metric and orientation in a
$n$-dimensional Euclidean space. Usually we are interested in its
3-dimensional realization, $SE(3)$, whose study forms the basis of
rigid body kinematics.

#+include: ~/org/latex.org

* Definition
   
  The affine property implies that any $g \in SE(3)$ acts on $x \in \RR^n$
  by: \[ g(x) = R.x + t \]

  where $R$ is an invertible linear map, and $t \in E$ is the
  translation part.
  
  The metric-invariance implies that the linear part must be an
  orthogonal endomorphism of $\RR^n$, and the orientation invariance
  forces the linear part to be a rotation, that is $R \in SO(n)$.

  It is worth noticing that any $g \in SE(3)$ is the composition of a
  /rotation/ followed by a /translation/:

  \[ g(x) = (t \circ R)(x) \]

* Group Operations
  
  - Product: \[ g_1.g_2(x) = R_1( R_2.x + t_2) + t_1 = R_1 R_2.x + R_1.t_2 + t_1 \]
  - Inverse: \[ \inv{g}(x) = \inv{(t \circ R)}(x) = (\inv{R} \circ \inv{t}) (x) = \inv{R}(x - t) \]
    
* Matrix Representation

  It is common to represent this group using homogeneous coordinates:

  \[ g \in SE(3) \simeq \mat{ R & t\\ 0 & 1} \]
  
  The action of $g \in SE(3)$ on a vector $x \in \RR^3$ is then given
  by:

  \[ \mat{ g(x) \\ 1} = \mat{ R & t\\ 0 & 1} \mat{x \\ 1} \]

** Product

	 \[ \mat{R_1 & t_1 \\ 0  & 1} \mat{R_2 & t_2 \\ 0  & 1} = \mat{ R_1.R_2 & R_1.t_2 + t_1 \\ 0 & 1} \]

** Inverse

	 \[ \mat{R & t \\ 0 & 1}^{-1} = \mat{R^T & -R^T t \\ 0  & 1 } \]
 
* Lie Group Structure

  Is is easy to verify that the above group operations make $SE(3)$ a
  [[file:lie-groups.org][Lie group]], since $SO(3)$ and $\RR^3$ are Lie groups. The matrix
  representation gives the Lie algebra as the $4 \times 4$ matrices of
  the form:

  \[ \kappa \in \mathfrak{se(3)} \simeq \mat{ \omega & v \\ 0 & 0} \] 
  
  where $\omega \in \mathfrak{so(3)}$ and $v \in \RR^3$. It is common
  to refer to Lie algebra elements by using their coordinates in the
  (6-dimensional) canonical basis. Such 6-vectors are also known as
  /twists/.
  
** Adjoint

   The adjoint representatio of the group is given in coordinates by
   the following mapping:

   \[ Ad_g \mat{\omega \\ v} = \mat{ R & 0 \\ \hat{t}R & R } \mat{\omega \\ v} 
   = \mat{ R \omega \\ t\times R\omega + R v } 
   \]

   where $\hat{t}$ is the antisymmetric $3 \times 3$ cross-product
   matrix: $\hat{t}.x = t \times x$.[fn:cross]

	 The adjoint representation of the algebra is given by:

	 \[ ad \mat{ \omega \\ v } = \mat{ \hat{\omega} & 0 \\  \hat{v} & \hat{\omega}} \]

** TODO Exponential

** TODO Logarithm

** TODO Bracket


* Kinematics

All in all, body-fixed quantities are much easier to work with.

** Twists
	 
	 Twists are 6-vectors built from the coordinates of Lie algebra
	 elements in the canonical basis :

	 \[ (\omega, v) \simeq \mat{\hat{\omega} & v \\ 0 & 0} \]

*** Body twist

	 - $\omega$ is the angular velocity of the frame in the frame coordinates
	 - $v$ is the velocity of the frame origin in the frame coordinates
		 
*** Spatial twist 

	 - $\omega$ is the angular velocity of the frame in absolute coordinates
	 - $v$ is the velocity of the absolute origin /as if it were attached to the moving frame/

	 This is because $v = \dot{t} - \omega \times t$ if you consider
     the velocity of the frame origin.

** Wrenches

	 In the same way, wrenches are 6-vectors built from the coordinates
	 of Lie coalgebra elements in the canonical basis :

	 \[ (\tau, f) \simeq \mat{\hat{\tau} & f \\ 0 & 0}^\star \]
	 
*** Body wrench

	- $\tau$ is the torque about the frame, expressed about the frame
      origin, in frame coordinates.
	  
	- $f$ is the force acting on the frame origin, expressed in the
      frame coordinates. 

	This is because $f^T \dot{t} = f^T R v$, so $R^T f$ is the linear,
    body-fixed force.

*** Spatial wrench
	
	- $f$ is the force acting on the frame origin, expressed in
      absolute coordinates.

	- $\tau$ is the torque acting on the frame, expressed at the world
      origin, in absolute coordinates.
		 
	To see this, we apply a torque/force pair on the frame:
	
	\begin{align*}
	\delta W &= \tau^T \omega + f^T \dot{t} \\
	&= \block{\tau + t \times f}^T \omega + f^T v \\
	\end{align*}
	
	We end up with the torque initially applied to the frame, plus
    the torque generated by applying the force on the frame origin,
    so the torque we get is about the absolute origin.
	

** Recap

	 \[ \ds g = Ad_g.\db g \]
	 
	 \[ f^b g = Ad_g^\star.f^s g\]

** Center of Pressure

	 

	 

** TODO Zero Momentum Point
   
   The adjoint transpose can be used to compute the so-called /Zero
   Momentum Point/ (ZMP) associated with a (body) wrench $F =(\tau, f)
   \in \mathfrak{se(3)}^\star$. We look for a (body) frame change $g
   \in SE(3)$ such as the applied torque vanishes in the equivalent
   wrench. In other words:

   \[ \tau_g = R^T \tau - R^T\hat{t}f = R^T(\tau- \hat{t} f) = 0 \]
   
   This implies that $f \times t = -\tau$, which is only a rank-2
   constraint. The constraint is not feasible as long as $\tau$ and
   $f$ are not orthogonal (/i.e./ there is a spinning torque along the
   net force), so in practice either the torque is minimized, or
   (equivalently, as the kernel of the constraint is exactly $f$) only
   non-spinning torque is considered:

	 \[ -\tau_\bot = f \times t  \]

	 Additional constraints must be added depending on the problem, such
   as that the ZMP should lie on the ground plane, in the case of an
   inverted pendulum model.
   

[fn:cross] More precisely: $\small{\hat{t} = \mat{0 & -t_3 & t_2 \\ t_3 & 0 & -t_1 \\ -t_2 & t_1 & 0}}$
   

  
 
 
 
